### ISSUE TITLE
About the type and structure of the training data directory

### ISSUE THREAD

**Issue by leefly072** [Xiaodong-Bran/MLFcGAN#1]
Hello, I tried to run related training and testing programs, but some problems occurred.
`TypeError: expected str, bytes or os.PathLike object, not NoneType
train.sh: 3: train.sh: --dataset_path: not found
`
If you have time or convenience, I would like to ask, the type and path format of the data on your side, if you can reply it will be very grateful. Looking forward to your reply, thank you.

**Comment by Xiaodong-Bran** [comment]
Hi,

First of all,  you need to prepare your training data, then modify the '--dataset_path'  in the train.sh accordingly.

**Comment by Xiaodong-Bran** [comment]
Hi,

I think, first of all, you need to prepare your training data and then modify the "--dataset_path" accordingly in the train.sh.
