### ISSUE TITLE
Train 

### ISSUE THREAD

**Issue by yudadabing** [Xiaodong-Bran/MLFcGAN#3]
Hello, I train the network on new datasets, I change the batch_size, the network will report an error. What should I do to avoid it?

**Comment by Xiaodong-Bran** [comment]
@yudadabing may I know what is the batch size you used and what was the error reported?

**Comment by yudadabing** [comment]
> @yudadabing may I know what is the batch size you used and what was the error reported?

When I set batch_size=8, I get  the error:

Traceback (most recent call last):
  File "train.py", line 101, in <module>
    gradient_penalty = calc_gradient_penalty(net_d, real_ab.data, fake_ab.data,opt,device)
  File "/media/db/CAD8DA7AD8DA646B/zzl/Restoration/MPRNet-main/MLFcGAN-master/utils.py", line 135, in calc_gradient_penalty
    alpha = alpha.expand(real_data.size())
RuntimeError: The expanded size of the tensor (256) must match the existing size (8) at non-singleton dimension 2.  Target sizes: [8, 6, 256, 256].  Tensor sizes: [8, 1]

**Comment by Xiaodong-Bran** [comment]
@yudadabing  hi , please consider to change the code from alpha = torch.rand(opt.batch_size, 1) to alpha = torch.rand(1, 1).

**Comment by yudadabing** [comment]
@yudadabing thanks, it works well following your tips.
