### ISSUE TITLE
Change image size

### ISSUE THREAD

**Issue by masie127** [Xiaodong-Bran/MLFcGAN#4]
Hello, is it possible to train or test with an image size greater than 256x256? If I pass a bigger picture for testing i always get the error:
> n, dims = concat_t.size()  # [512]
> ValueError: too many values to unpack (expected 2)

in get_global_copy(tensor,height,width,shrink=None).
The concat_t.size() of an 256x256 image is [1,512] and for a bigger image [1,512,15,15].
It is very important that i can improve larger pictures.

I am very grateful for help.

**Comment by Xiaodong-Bran** [comment]
@masie127 Hi, so far the network is tailored for the 256*256 image size. You may consider changing the network params accordingly for larger images.

Thanks.
