### ISSUE TITLE
New generator

### ISSUE THREAD

**Issue by Ostrich5yw** [Xiaodong-Bran/MLFcGAN#5]
hello,I used a new generator that I built myself,and I found that there were a lot of noise points in the training results.
In this network, could a new generator or discriminator be used to replace the existing one(like unetsimple8Global)?
![predict_1](https://user-images.githubusercontent.com/72113963/131446700-63c34b13-718d-4b10-a05e-50530867f727.png)
I am very grateful for help.

**Comment by Xiaodong-Bran** [comment]
@Ostrich5yw  
Yes, you can replace the generator or discriminator but the performance is not guaranteed. 
For the noisy results, is it due to insufficient training? 
You may monitor the training process and check the performance per epoch.
